In [1]:
import numpy as np

In [2]:
c = np.random.random((5 ,5))

In [6]:
c[3:5, 2:4] = 37

In [7]:
c

array([[3.11949328e-01, 6.58586477e-02, 3.69034744e-01, 9.32401087e-01,
        4.77206009e-01],
       [3.21205097e-02, 7.94186361e-01, 2.65260212e-01, 7.19757262e-01,
        2.43420365e-01],
       [9.66283326e-01, 4.37421365e-01, 1.05406316e-01, 9.58612815e-01,
        2.16886698e-01],
       [1.90337390e-01, 6.68948842e-01, 3.70000000e+01, 3.70000000e+01,
        4.87476226e-01],
       [2.78997722e-01, 9.51760165e-01, 3.70000000e+01, 3.70000000e+01,
        6.71811954e-02]])

In [17]:
v1 = np.array([1,2,7])
v2 = np.array([3,4,9])

In [22]:
def f(a,b):
    return a+b

In [19]:
f(v1,v2)

(array([1, 2, 7]), array([3, 4, 9]))

In [25]:
v = np.array([v1, v2])

In [21]:
v

array([[1, 3],
       [2, 4],
       [7, 9]])

In [27]:
f(*v)

array([ 4,  6, 16])

In [28]:
m1 = np.random.random((3,3))
m2 = -np.random.random((3,3))

In [33]:
M = np.array([m1,m2])

In [36]:
M2 = f(*M)

In [39]:
M2

array([[ 0.28216392,  0.4068661 , -0.62119146],
       [ 0.1693847 ,  0.67231405,  0.57236131],
       [-0.34718278, -0.41463619,  0.1927015 ]])

In [40]:
def gen(x, y):
    return 5.3 * np.log(x) -3.4 * x / y

In [48]:
gen(*v)

array([-1.13333333,  1.97368006,  7.66887935])