In [2]:
import numpy as np

In [2]:
c = np.random.random((5 ,5))

In [6]:
c[3:5, 2:4] = 37

In [7]:
c

array([[3.11949328e-01, 6.58586477e-02, 3.69034744e-01, 9.32401087e-01,
        4.77206009e-01],
       [3.21205097e-02, 7.94186361e-01, 2.65260212e-01, 7.19757262e-01,
        2.43420365e-01],
       [9.66283326e-01, 4.37421365e-01, 1.05406316e-01, 9.58612815e-01,
        2.16886698e-01],
       [1.90337390e-01, 6.68948842e-01, 3.70000000e+01, 3.70000000e+01,
        4.87476226e-01],
       [2.78997722e-01, 9.51760165e-01, 3.70000000e+01, 3.70000000e+01,
        6.71811954e-02]])

In [17]:
v1 = np.array([1,2,7])
v2 = np.array([3,4,9])

In [22]:
def f(a,b):
    return a+b

In [19]:
f(v1,v2)

(array([1, 2, 7]), array([3, 4, 9]))

In [25]:
v = np.array([v1, v2])

In [21]:
v

array([[1, 3],
       [2, 4],
       [7, 9]])

In [27]:
f(*v)

array([ 4,  6, 16])

In [28]:
m1 = np.random.random((3,3))
m2 = -np.random.random((3,3))

In [33]:
M = np.array([m1,m2])

In [36]:
M2 = f(*M)

In [39]:
M2

array([[ 0.28216392,  0.4068661 , -0.62119146],
       [ 0.1693847 ,  0.67231405,  0.57236131],
       [-0.34718278, -0.41463619,  0.1927015 ]])

In [40]:
def gen(x, y):
    return 5.3 * np.log(x) -3.4 * x / y

In [48]:
gen(*v)

array([-1.13333333,  1.97368006,  7.66887935])

In [56]:
n = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])

In [57]:
n.shape

(2, 3, 4)

In [76]:
a = np.array([[-.3,-.4,-.5],[-.6,-.7,-.8]]).T
a

array([[-0.3, -0.6],
       [-0.4, -0.7],
       [-0.5, -0.8]])

In [75]:
a.shape

(3, 2)

In [77]:
np.tensordot(n,a, axes=([0,1],[1,0]))

array([-43.3, -46.6, -49.9, -53.2])

np.tensordot(n,a, axes=([0,1],[1,0]))

In [82]:
n.transpose((1,0,2)).shape

(3, 2, 4)

In [6]:
v1 = np.array([1,2,3,4])
v2 = np.array([7,8,9,0])

In [31]:
num = v1.reshape((1,4)) - v2.reshape((4,1))

In [8]:
u = np.array([1,2,3,4])

In [25]:
def diff(x,y):
    if x.all() == y.all() :
        return 1
    else:
        return x - y

In [30]:
den = u.reshape((1,4)) - u.reshape((4,1)) + np.identity(4)

In [32]:
m1 = np.ones((2,2))

In [33]:
m2 = 2 * m1
m3 = 3 * m1
m4 = 4 * m1

In [34]:
mm = np.array([m1,m2,m3,m4])

In [35]:
mm.shape

(4, 2, 2)

In [36]:
np.prod(mm, axis=0)

array([[24., 24.],
       [24., 24.]])

In [430]:
e = np.linspace(0.1, 1, 10)
q = np.linspace(0.1, 1,  3)

n_e_points = e.shape[0]
n_q_points = q.shape[0]

In [431]:
basis = np.ones((n_e_points, n_q_points), dtype=np.float64)
b = np.ones((n_e_points, n_q_points, n_q_points), dtype=np.float64)
    
for i in range(n_e_points):
    for j in range(n_q_points):
        for k in range(n_q_points):
            if k == j:
                continue
            b[i, j, k] = (e[i] - q[k]) / (q[j] - q[k])

In [432]:
num = e.reshape((n_e_points, 1)) - q
num

array([[ 0.  , -0.45, -0.9 ],
       [ 0.1 , -0.35, -0.8 ],
       [ 0.2 , -0.25, -0.7 ],
       [ 0.3 , -0.15, -0.6 ],
       [ 0.4 , -0.05, -0.5 ],
       [ 0.5 ,  0.05, -0.4 ],
       [ 0.6 ,  0.15, -0.3 ],
       [ 0.7 ,  0.25, -0.2 ],
       [ 0.8 ,  0.35, -0.1 ],
       [ 0.9 ,  0.45,  0.  ]])

In [433]:
den = q.reshape((n_q_points, 1)) - q - np.identity(n_q_points)
den

array([[-1.  , -0.45, -0.9 ],
       [ 0.45, -1.  , -0.45],
       [ 0.9 ,  0.45, -1.  ]])

In [425]:
den_r = den.reshape((1, n_q_points, n_q_points))
num_r = num.reshape((n_e_points, 1, n_q_points))
n, d = np.broadcast_arrays(num_r, den_r)
#for k in range(n.shape[0]):
#    np.fill_diagonal(n[k,:,:], 1)
#    np.fill_diagonal(d[k,:,:], 1)
#num_r[:,np.arange(num_r.shape[1]), np.arange(num_r.shape[2])] = 1

In [434]:
prod = num_r / den_r
#for k in range(prod.shape[0]):
#    np.fill_diagonal(prod[k,:,:], 1)

In [435]:
#for k in range(prod.shape[0]):
#    np.fill_diagonal(prod[k,:,:], 1)
ar = np.arange(prod.shape[1])
prod[:,ar,ar] = 1

In [436]:
prod.shape

(10, 3, 3)

In [437]:
prod == b

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

In [441]:
v1[:,...]

array([1, 2, 3, 4])